39 gyroscope subsystem
BadRobots1014/BadRobot2023 pull request #47
Opened 2023-02-09 00:06 UTC by noiritgc

2023-02-09 00:33 UTC, JavaBlendPhilippe commented on src/main/java/frc/robot/RobotContainer.java
> +    lightButton.whileTrue(this.m_balancecommand);
Would change name to not be light button unless the primary purpose of this button is the lights. Just reading it looks more like this button is for balancing, so the name lightButton is very misleading
```suggestion
    JoystickButton balanceButton = new JoystickButton(this.leftJoystick, ControllerConstants.kBalanceButton);
    balanceButton.whileTrue(this.m_balancecommand);
```

2023-02-09 00:39 UTC, JavaBlendPhilippe commented on src/main/java/frc/robot/commands/BalanceCommand.java
> +    /*if(angle >= 5 && angle < 10){
No Explanation for why this commented out code should be saved, Noirit says the stuff above is the working one, remove this it takes a lot of line space. Either comment explaining its use case or remove.

2023-02-09 00:42 UTC, JavaBlendPhilippe requested changes
Looking pretty solid, left some comments on stuff that should be changed, fix those real quic

2023-02-09 00:43 UTC, dCellar commented on src/main/java/frc/robot/commands/BalanceCommand.java
> +    }*/
Remove this comment
```suggestion
```

2023-02-11 19:27 UTC, Fyrefyte approved these changes

2023-02-11 19:34 UTC, merged